from functions.get_file_content import get_file_content

print("Result for lorem.txt:")
result_1 = get_file_content("calculator", "lorem.txt")
length = len(result_1[:10000])
truncate = result_1.endswith(f'truncated at 10000 characters]')
print(f"    {length}")
print (f"   {truncate}")
print("Result for calculator.py:")
result_2 = get_file_content("calculator", "main.py")
print(f"    {result_2}")
print("Result for calculator.py:")
result_3 = get_file_content("calculator", "pkg/calculator.py")
print(f"    {result_3}")
print("Result for '/bin/cat':")
result_4 = get_file_content("calculator", "/bin/cat")
print(f"    {result_4}")
print("Result for does_not_exist.py:")
result_5 = get_file_content("calculator", "pkg/does_not_exist.py")
print(f"    {result_5}")
