from functions.run_python_file import run_python_file
result_1 = run_python_file("calculator", "main.py")
result_2 = run_python_file("calculator", "main.py", ["3 + 5"])
result_3 = run_python_file("calculator", "tests.py")
result_4 = run_python_file("calculator", "../main.py")
result_5 = run_python_file("calculator", "nonexistent.py")
result_6 = run_python_file("calculator", "lorem.txt")
print("Result for calculator, main.py:")
print(f"    {result_1}")
print("result for calculator, main.py, [3 + 5]:")
print(f"    {result_2}")
print("result for calculator, tests.py:")
print(f"    {result_3}")
print("result for calculator, ../main.py")
print(f"    {result_4}")
print("result for calculator, nonexistant.py:")
print(f"    {result_5}")
print("result from calculator, lorem.txt:")
print(f"    {result_6}")
